# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  optparse os pathlib pprint re sys xml.etree.ElementTree zipfile hashlib logging time
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run_valid
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 ${WORKSPACE}validateArchive.py -f ${WORKSPACE}/STM32CubeH7 --skip ".*__INTERNAL__.*"
